### ISSUE TITLE
ConfigUtils中使用Properties，导致读取boolean、integer等会返回null

### ISSUE THREAD

**Issue by foreveryang321** [apache/incubator-dubbo#2055]
https://github.com/apache/incubator-dubbo-spring-boot-project/issues/60

dubbo-spring-boot-starter.0.2.0.jar
dubbo.2.6.2.jar

application.yml
```yml
dubbo:
  consumer:
    check: false
```
调用ConfigUtils.replaceProperty(properties.getProperty(key, defaultValue), (Map) properties)读取配置时，返回 null，java.util.Properties.getProperty源码如下
![42026035-aa059c2e-7af8-11e8-8b6f-80ca38a3d128](https://user-images.githubusercontent.com/5868190/42442936-a32d267a-839e-11e8-9bde-546e0c8f5804.png)

暂时的解决方案
```yml
dubbo:
  consumer:
    check: 'false'
```
