### ISSUE TITLE
[2.7.0-development docs] Background

### ISSUE THREAD

**Issue by chickenlj** [apache/incubator-dubbo#2910]
## 总体目标

在2.7.0版本中，Dubbo提出了将注册中心和服务治理中心分离的思想，概念上向时下流行的微服务注册中心、配置中心模型看齐。同时在此基础上，2.7.0版本又额外引入了一个元数据中心，通过更丰富的元数据内容进一步提高服务治理能力。

![threecenters](https://user-images.githubusercontent.com/18097545/49638277-aeaa9300-fa42-11e8-9eb7-c876cd33a4c1.jpg)

从每个中心的职责划分的角度，我们期望带来的好处是：

- 注册中心。通过裁剪冗余的URL数据，减轻配置中心的存储和推送压力
- 配置中心。让开发者可以对接微服务场景下更常用的、更专业的配置中心，如Nacos, Apollo, Consul, Etcd等。如果按不同的生命周期阶段划分，配置中心在Dubbo中承担了如下几个角色。
  - 启动阶段的配置管控。类似Spring Cloud Config实现External Configuration管控。
  - 运行期的服务治理。从2.6及之前版本的注册中心中剥离出来的服务治理能力，运行期存储并推送各种覆盖规则、路由规则等
  - 运行期的配置变更读取。Dubbo的一些，目前框架内仅在非核心的RPC链路上读取，如启动销毁阶段，并且开放给用户使用。
- 元数据中心。尽可能多的注册服务的元数据到此中心，例如方法名列表、方法签名、方法参数类型定义等，为实现服务测试、mock提供可能，这部分的存储实现将是可扩展的，包括zookeeper, redis等。

## 工作原理

以Dubbo应用的生命周期描述，对比之前单注册中心的工作模式，Dubbo的工作流程如下：

![workflow](https://user-images.githubusercontent.com/18097545/49638287-b36f4700-fa42-11e8-9fdd-9aa5a23d0769.jpg)

## 示例说明

平时在Dubbo中我们接触最多的就是一长串的URL，接下来，我们就以一个简单URL为例来说明2.7版本带来的变化。

### 典型URL

以下是一个典型的Dubbo注册中心URL（2.6及以前版本）

> dubbo://ip:port/org.apache.dubbo.compose.ic.service.vas.ValueAddServiceCompose?anyhost=true&application=dubbo-demo&default.actives=400&default.delay=-1&default.dispatcher=all&default.group=online&default.loadbalance=leastactive&default.service.filter=-monitor&default.threads=400&default.timeout=2000&default.version=1.0&delay=1&dubbo=3.0.5.1&environment=product&interface= org.apache.dubbo.compose.ic.service.vas.ValueAddServiceCompose&logger=slf4j&methods=queryValueAddServiceEditVOs,auditPassByValueAddServiceIdList,getValueAddServiceVOByServiceIds,getValueAddServiceInfoByGoodsIdList,getRuleMatchVOByGoodsIdList,getValueAddServiceEditVOById,getValueAddServiceEditVOByIds,queryValueAddServiceVOs,disableValueAddService,auditRejectByValueAddServiceIdList,saveValueAddServiceEditVO,enableValueAddService&organization=dubbo-demo&owner=John&pid=54812&revision=1.0.0&sentry_target_cluster_name=dubbo-demo-test&side=provider×tamp=1530671441040

在一些企业的大规模实践的基础上，我们逐渐发现这样组织的注册中心URL存在一些问题：

- 注册中心存储的URL过长，导致存储压力骤增，变更事件的推送效率明显下降；同时给订阅方带来了额外的计算压力，尤其是大规模实例场景下的内存增长显著。
- 注册中心承担了过多服务治理配置的功能：负责初始配置的同步，同时负责存储各种运行期配置规则。这一方面加剧了注册中心的压力，另一方面配置规则的灵活性也受到了一定的限制，同时也无法利用一些更专业的微服务配置中心带来的强大功能。
- 服务的元数据过于简略，如我们只有methods, pid, owner等，但为更详细的了解服务状态，我们需要尽可能多的属性，尽可能丰富的服务元数据。以methods为例，虽然方法列表的内容已经很长了，但当我们要在OPS开发服务测试/mock功能时，却发现需要的方法签名等数据还是无法获取。

### 按作用拆分

对应以上问题，我们先简单的将URL中的内容划分为3部分：

1. Endpoint地址

   dubbo://ip:port/org.apache.dubbo.compose.ic.service.vas.ValueAddServiceCompose

2. 需要同步或治理的服务数据default.actives=400&default.delay=-1&default.dispatcher=all&default.group=online&default.loadbalance=leastactive&default.service.filter=-monitor&default.threads=400&default.timeout=2000

3. 服务查询、监控需要的元数据methods=queryValueAddServiceEditVOs,auditPassByValueAddServiceIdList,getValueAddServiceVOByServiceIds,getValueAddServiceInfoByGoodsIdList,getRuleMatchVOByGoodsIdList,getValueAddServiceEditVOById,getValueAddServiceEditVOByIds,queryValueAddServiceVOs,disableValueAddService,auditRejectByValueAddServiceIdList,saveValueAddServiceEditVO,enableValueAddService&organization=dubbo-demo&owner=John&pid=54812&revision=1.0.0&sentry_target_cluster_name=dubbo-demo-test

### 映射到3个中心

对于第1部分，是服务自动发现的核心，我们还是继续要通过注册中心来实现同步，同时鉴于Dubbo当前基于服务粒度的服务发现模型，第2部分中部分内容我们也将在2.7.0的URL中仍继续保留，一方面是为向前保持兼容性，另一方面也是为服务治理提供最大的可能性，所以最终我们发送到注册中心的数据格式是：

> dubbo://ip:port/org.apache.dubbo.compose.ic.service.vas.ValueAddServiceCompose?group=online&timeout=2000

对于第2部分的数据，也是Dubbo的动态配置覆盖规则关注的部分，2.7.0开始，我们将覆盖规则下发到配置中心，由配置中心负责规则的推送，同时定义了更灵活的、多维度的覆盖规则格式：

```yaml
---
apiVersion: v2.7
scope: application/service
key: governance-appoverride-provider/group+service+version
enabled: true
configs:
- addresses: ["0.0.0.0"] # must not contain port when works on consumer side
  providerAddresses: ["1.1.1.1:20880", "2.2.2.2:20881"] # must contain port
  applications/services: []
  parameters:
    timeout: 1000
    cluster: failfase
    loadbalance: random
- addresses: ["0.0.0.0:20880"] # must contain port when works on provider side, specify multiple addresses if you want to apply to multiple ports.
  applications/services: []
  parameters:
    threadpool: fixed
    threads: 200
    iothreads: 4
    dispatcher: all
    queues: 0
    weight: 200
...
```

最后，服务查询和监控数据，2.7.0的原则是尽可能的予以丰富，所以在保留第3部分全部数据的基础上，又增加了服务方法签名的元数据：

```text

```
