### ISSUE TITLE
[Enhancement] Simplify externalized configuration of Dubbo Protocol name

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo#3189]
For now, Dubbo Protocol has to specify  its' name in externalized configuration, e.g:

```yaml
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: 12345
    rest:
      name: rest
      port: 9090
      server: netty
```

Obviously, `dubbo.protocols.dubbo.name=dubbo` is unnecessary and could be simplified, thus, if ${id} will be used as protocol name in properties pattern like `dubbo.protocols.${id}.*` .
