### ISSUE TITLE
dubbo.registry.file路径解析异常

### ISSUE THREAD

**Issue by linzhiqiang0514** [apache/incubator-dubbo#3509]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: macOs
* Java version: 1.8.0

### Steps to reproduce this issue

1. 引用dubbo-spring-boot-start-2.7.0
2. 配置属性
```
dubbo:
  application:
#    name: ${spring.applicaiton.name}
    qos-enable: false
  registry:
#    address: zookeeper://localhost:2181
    file: ${user.home}/dubbo-cache/${dubbo.applicaiton.name}/dubbo.cache
#    username: admin
#    password: 123456
    group: dubbo
    simplified: true
```
3. 或者使用：
```
 file: ${user.home}/dubbo-cache/${spring.applicaiton.name}/dubbo.cache
```
Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
期望生成 
```
/user/xxxx/dubbo-cache/app名称/dubbo.cache
```

What do you expected from the above steps？

### Actual Result

```
➜  dubbo-cache pwd
/Users/linzhiqiang/dubbo-cache
➜  dubbo-cache ls -lsh
total 0
0 drwxr-xr-x  4 linzhiqiang  staff   128B  2 20 09:54 ${dubbo.applicaiton.name}
0 drwxr-xr-x  4 linzhiqiang  staff   128B  2 19 15:17 ${spring.applicaiton.name}
```

实际上这个变量并没有解析。
```
{"ApplicationConfig":{"org.apache.dubbo.config.ApplicationConfig#0":{"architecture":null,"class":"org.apache.dubbo.config.ApplicationConfig","compiler":null,"dumpDirectory":null,"environment":null,"id":"testDaoApp","logger":null,"name":"testDaoApp","organization":null,"owner":null,"prefix":"dubbo.application","qosAcceptForeignIp":null,"qosEnable":false,"qosPort":null,"registryIds":null,"shutwait":null,"valid":true,"version":null}},"ConsumerConfig":
```
application.name属性是存在的。

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
